version: "3.1"

services:
  
  nginx:
    image: amrmrp/php-laravel:latest
    container_name: web
    ports:
      - "81:8000"
    volumes:
      - ${PWD}:/var/www/html/
    depends_on:
     - db
    command: bash -c "php artisan serve --host 0.0.0.0 --port 8000"

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3308:3306"
  

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyAdmin
    restart: always
    ports:
      - "82:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_ARBITRARY=db

volumes:
  laravel-mysql:
    driver: local